In [338]:
import pandas as pd

blr = pd.read_csv(r"C:\Users\CFRSI 11\Desktop\Machine Learning Project\Bengaluru_House_Data.csv")

blr.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [339]:
blr.tail()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.0
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.0
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.0
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.0
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.0

In [340]:
blr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [341]:
blr.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [342]:
blr.describe(include='all')

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
count,13320,13320,13319,13304,7818,13320,13247.000000,12711.000000,13320.000000
unique,4,81,1305,31,2688,2117,NaN,NaN,NaN
top,Super built-up Area,Ready To Move,Whitefield,2 BHK,GrrvaGr,1200,NaN,NaN,NaN
freq,8790,10581,540,5199,80,843,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,2.692610,1.584376,112.565627
std,NaN,NaN,NaN,NaN,NaN,NaN,1.341458,0.817263,148.971674
min,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,8.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,1.000000,50.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,72.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,2.000000,120.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,40.000000,3.000000,3600.000000

In [343]:
blr.shape

(13320, 9)

In [344]:
blr.size

119880

In [345]:
blr.columns.tolist()

['area_type',
 'availability',
 'location',
 'size',
 'society',
 'total_sqft',
 'bath',
 'balcony',
 'price']

In [346]:
print("\n Missing values per coloum: ", blr.isnull().sum())

 Missing values per coloum:  area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [347]:
blr.dtypes

area_type        object
availability     object
location         object
size             object
society          object
total_sqft       object
bath            float64
balcony         float64
price           float64
dtype: object

In [348]:
blr.index

RangeIndex(start=0, stop=13320, step=1)

In [349]:
location_list = blr["location"]
print(location_list.head())

0    Electronic City Phase II
1            Chikka Tirupathi
2                 Uttarahalli
3          Lingadheeranahalli
4                    Kothanur
Name: location, dtype: object

In [350]:
print(type(location_list))

<class 'pandas.core.series.Series'>

In [351]:
blr.drop(columns = ["society"],inplace = True)

In [352]:
blr.shape

(13320, 8)

In [353]:
blr.isnull().sum()

area_type         0
availability      0
location          1
size             16
total_sqft        0
bath             73
balcony         609
price             0
dtype: int64

In [354]:
blr.dropna(inplace = True)

In [355]:
blr.isnull().sum()

area_type       0
availability    0
location        0
size            0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [356]:
print(location_list.head())
print(location_list.tail())

0    Electronic City Phase II
1            Chikka Tirupathi
2                 Uttarahalli
3          Lingadheeranahalli
4                    Kothanur
Name: location, dtype: object
13315               Whitefield
13316            Richards Town
13317    Raja Rajeshwari Nagar
13318          Padmanabhanagar
13319             Doddathoguru
Name: location, dtype: object

In [357]:
print(blr["location"].value_counts())

location
Whitefield            514
Sarjapur  Road        372
Electronic City       300
Kanakpura Road        261
Thanisandra           231
                     ...
Milk Colony             1
Sundara Nagar           1
Jaladarsini Layout      1
Madanayakahalli         1
Abshot Layout           1
Name: count, Length: 1265, dtype: int64

In [358]:
blr["location"] = blr["location"].apply(lambda x: x.strip())

In [359]:
blr.location.value_counts()

location
Whitefield          515
Sarjapur  Road      372
Electronic City     302
Kanakpura Road      261
Thanisandra         234
                   ...
Shirdi Sai Nagar      1
S R Layout            1
Meenakshi Layout      1
Vidyapeeta            1
Abshot Layout         1
Name: count, Length: 1254, dtype: int64

In [360]:
locatio_stats = blr.groupby('location')['location'].agg('count').sort_values(ascending =  False)

In [361]:
locatio_stats

location
Whitefield              515
Sarjapur  Road          372
Electronic City         302
Kanakpura Road          261
Thanisandra             234
                       ...
Kanakapura  Rod           1
Kanakapura Main Road      1
Kanakapura Road           1
Kanakapura Road,          1
whitefiled                1
Name: location, Length: 1254, dtype: int64

In [362]:
less_than_10_entries = locatio_stats[locatio_stats <= 10]

In [363]:
blr['location'] = blr['location'].apply(lambda  x: "other" if x in less_than_10_entries else x)

In [364]:
blr.location.value_counts()

location
other                        2739
Whitefield                    515
Sarjapur  Road                372
Electronic City               302
Kanakpura Road                261
                             ...
Marsur                         11
LB Shastri Nagar               11
2nd Phase Judicial Layout      11
ISRO Layout                    11
Vishveshwarya Layout           11
Name: count, Length: 238, dtype: int64

In [365]:
ll = "     hello "
ll.strip()

'hello'

In [366]:
blr["size"].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '3 Bedroom', '1 BHK', '1 RK',
       '4 BHK', '1 Bedroom', '2 Bedroom', '6 Bedroom', '8 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '11 Bedroom', '43 Bedroom',
       '14 BHK', '8 BHK', '12 Bedroom', '10 Bedroom', '13 BHK'],
      dtype=object)

In [367]:
blr['bedrooms'] = blr['size'].apply(lambda x:int(x.split(' ')[0]))

In [368]:
blr.tail()

,area_type,availability,location,size,total_sqft,bath,balcony,price,bedrooms
13314,Super built-up Area,Ready To Move,Green Glen Layout,3 BHK,1715,3.0,3.0,112.0,3
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,3453,4.0,0.0,231.0,5
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,1141,2.0,1.0,60.0,2
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,4689,4.0,1.0,488.0,4
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,550,1.0,1.0,17.0,1

In [369]:
blr['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(1976,), dtype=object)

In [370]:
def clean(sqft):
    tokens = sqft.split('-')
    if len(tokens) == 2:
        return ((float(tokens[0])) + (float(tokens[1])))//2
    else:
        try:
            return float(sqft)
        except:
            return None

In [371]:
clean('100')

100.0

In [372]:
clean('100-200')

150.0

In [373]:
blr['total_sqft'] = blr['total_sqft'].apply(clean)

In [374]:
blr['total_sqft'].unique()

array([1056., 2600., 1440., ..., 2758.,  774., 4689.], shape=(1849,))

In [375]:
blr['sqft_per_bed'] =blr['total_sqft']/blr['bedrooms']

In [376]:
blr.head()

,area_type,availability,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bed
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.0
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.0
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.0
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.0
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.0

In [377]:
blr['sqft_per_bed'].head()

0    528.0
1    650.0
2    480.0
3    507.0
4    600.0
Name: sqft_per_bed, dtype: float64

In [378]:
data2 = blr[blr['sqft_per_bed']>=300]

In [379]:
data2['sqft_per_bed'].describe()

count    12013.000000
mean       590.449630
std        379.862152
min        300.000000
25%        490.000000
50%        560.000000
75%        626.000000
max      26136.000000
Name: sqft_per_bed, dtype: float64

In [380]:
data2['sqft_per_price'] = blr['price']*100000/blr['total_sqft']

C:\Users\CFRSI 11\AppData\Local\Temp\ipykernel_15640\1875103194.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['sqft_per_price'] = blr['price']*100000/blr['total_sqft']

In [381]:
data2['sqft_per_price'].describe()

count     12013.000000
mean       6206.093629
std        3985.514984
min         267.829813
25%        4199.363057
50%        5252.673797
75%        6823.529412
max      176470.588235
Name: sqft_per_price, dtype: float64

In [382]:
data3 = data2[data2['sqft_per_price'] >= 2000 ]

In [383]:
data3['sqft_per_price'].describe()

count     11985.000000
mean       6217.550935
std        3983.024389
min        2000.000000
25%        4200.000000
50%        5263.157895
75%        6832.861190
max      176470.588235
Name: sqft_per_price, dtype: float64

In [384]:
data3.head()

,area_type,availability,location,size,total_sqft,bath,balcony,price,bedrooms,sqft_per_bed,sqft_per_price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,1056.0,2.0,1.0,39.07,2,528.0,3699.810606
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,2600.0,5.0,3.0,120.00,4,650.0,4615.384615
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,1440.0,2.0,3.0,62.00,3,480.0,4305.555556
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,1521.0,3.0,1.0,95.00,3,507.0,6245.890861
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,1200.0,2.0,1.0,51.00,2,600.0,4250.000000

In [406]:
data3.drop(columns  =  ['size','area_type', 'availability',  'sqft_per_bed','sqft_per_price'], axis = 1,inplace = True)

C:\Users\CFRSI 11\AppData\Local\Temp\ipykernel_15640\4038692216.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data3.drop(columns  =  ['size','area_type', 'availability',  'sqft_per_bed','sqft_per_price'], axis = 1,inplace = True)

In [407]:
data3.head()

                   location  total_sqft  bath  balcony   price  bedrooms
0  Electronic City Phase II      1056.0   2.0      1.0   39.07         2
1          Chikka Tirupathi      2600.0   5.0      3.0  120.00         4
2               Uttarahalli      1440.0   2.0      3.0   62.00         3
3        Lingadheeranahalli      1521.0   3.0      1.0   95.00         3
4                  Kothanur      1200.0   2.0      1.0   51.00         2

In [408]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11985 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    11985 non-null  object
 1   total_sqft  11985 non-null  float64
 2   bath        11985 non-null  float64
 3   balcony     11985 non-null  float64
 4   price       11985 non-null  float64
 5   bedrooms    11985 non-null  int64
dtypes: float64(4), int64(1), object(1)
memory usage: 655.4+ KB

In [409]:
#Sci-kit  Learn
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [410]:
from sklearn.model_selection import train_test_split

In [411]:
from sklearn.linear_model import LinearRegression

In [412]:
from sklearn.pipeline import make_pipeline

In [413]:
from sklearn.compose import make_column_transformer

In [414]:
col_trans = make_column_transformer(
    (OneHotEncoder(
        sparse_output = False,
        handle_unknown = 'ignore'
    ),
     ['location']
     ),
    remainder = 'passthrough'
)

In [415]:
lr = LinearRegression()

In [416]:
scaler = StandardScaler()

In [417]:
model = make_pipeline(col_trans,scaler,lr)

In [418]:
data3.head()

                   location  total_sqft  bath  balcony   price  bedrooms
0  Electronic City Phase II      1056.0   2.0      1.0   39.07         2
1          Chikka Tirupathi      2600.0   5.0      3.0  120.00         4
2               Uttarahalli      1440.0   2.0      3.0   62.00         3
3        Lingadheeranahalli      1521.0   3.0      1.0   95.00         3
4                  Kothanur      1200.0   2.0      1.0   51.00         2

In [419]:
X = data3.drop(columns=['price'])

In [420]:
y = data3['price']

In [421]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [422]:
import numpy as np

In [423]:
model.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [424]:
model.score(X_test,y_test)

0.6608852924169264

In [ ]:
input = pd.DataFrame([['Lingadheeranhalli',1000.0,2.0,1.0,2]], columns = ['location',	total_sqft	bath	balcony	price	bedroom]